In [56]:
import numpy as np
import itertools

a = [[[1,2,3],[4,5,6]],[[10,12,13],[14,15,16]],[[20,22,23],[24,25,26]]]
b=[1,2,3]



#a=np.array(a,dtype='int')
#b=np.array(b,dtype='int')

print(a)
print(b)
c=list(zip(a,b))
d=np.random.shuffle(c)
print(c)

#print(a.shape)
#print(b.shape)
#print(d)

image,label=zip(*c)
print('*'*20)
image=np.array(image,dtype='int')
label=np.array(label,dtype='int')
print(image)
print(label)

[[[1, 2, 3], [4, 5, 6]], [[10, 12, 13], [14, 15, 16]], [[20, 22, 23], [24, 25, 26]]]
[1, 2, 3]
[([[10, 12, 13], [14, 15, 16]], 2), ([[20, 22, 23], [24, 25, 26]], 3), ([[1, 2, 3], [4, 5, 6]], 1)]
********************
[[[10 12 13]
  [14 15 16]]

 [[20 22 23]
  [24 25 26]]

 [[ 1  2  3]
  [ 4  5  6]]]
[2 3 1]
